"""Public contracts for Studio view providers."""

from marimo_studio.view_providers._mounts import mount_attribute
from marimo_studio.view_providers._operation import (
    ProviderCancellation,
    ProviderCommandResult,
    ProviderRunner,
)
from marimo_studio.view_providers._records import (
    PROVIDER_API_VERSION,
    BuildProfile,
    BuildRequest,
    BuildResult,
    DocumentAccess,
    InspectionRequest,
    JsonValue,
    MountDeclaration,
    ProjectDiagnostic,
    ProjectInput,
    ProjectInputKind,
    ProjectInspection,
    ProjectionKind,
    ProviderAvailability,
    ProviderInfo,
    ProviderStarter,
    SourceDocument,
    SourceLocation,
    StarterContext,
    ViewProject,
    ViewProvider,
)

__all__ = [
    "PROVIDER_API_VERSION",
    "BuildProfile",
    "BuildRequest",
    "BuildResult",
    "DocumentAccess",
    "InspectionRequest",
    "JsonValue",
    "MountDeclaration",
    "ProjectDiagnostic",
    "ProjectInput",
    "ProjectInputKind",
    "ProjectInspection",
    "ProjectionKind",
    "ProviderAvailability",
    "ProviderCancellation",
    "ProviderCommandResult",
    "ProviderInfo",
    "ProviderRunner",
    "ProviderStarter",
    "SourceDocument",
    "SourceLocation",
    "StarterContext",
    "ViewProject",
    "ViewProvider",
    "mount_attribute",
]
