import { StyleSheet } from "@react-pdf/renderer";

import { palette, typefaces } from "./theme.ts";

export const styles = StyleSheet.create({
  page: {
    position: "relative",
    paddingTop: 30,
    paddingRight: 34,
    paddingBottom: 40,
    paddingLeft: 34,
    backgroundColor: palette.paper,
    color: palette.ink,
    fontFamily: typefaces.body,
    fontSize: 9,
    lineHeight: 1.35,
  },
  topline: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 9,
    borderBottomWidth: 0.6,
    borderBottomColor: palette.rule,
  },
  meta: {
    color: palette.fog,
    fontFamily: typefaces.body,
    fontWeight: 500,
    fontSize: 6.5,
    letterSpacing: 0.6,
  },
  pageTitle: {
    marginTop: 24,
    fontFamily: typefaces.display,
    fontSize: 33,
    lineHeight: 0.98,
    letterSpacing: -1.2,
  },
  pageLead: {
    width: "68%",
    marginTop: 10,
    color: palette.slate,
    fontSize: 10,
    lineHeight: 1.45,
  },
  sectionHeading: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  sectionIndex: {
    color: palette.orange,
    fontFamily: typefaces.body,
    fontSize: 6.2,
    fontWeight: 600,
    letterSpacing: 0.85,
  },
  sectionTitle: {
    marginTop: 2,
    fontFamily: typefaces.display,
    fontSize: 15,
  },
  sectionNote: {
    maxWidth: 170,
    color: palette.fog,
    fontSize: 7,
    textAlign: "right",
  },
  rule: {
    height: 0.6,
    backgroundColor: palette.rule,
  },
  metricRow: {
    flexDirection: "row",
    borderTopWidth: 0.6,
    borderBottomWidth: 0.6,
    borderColor: palette.rule,
  },
  metric: {
    flexGrow: 1,
    flexBasis: 0,
    paddingTop: 11,
    paddingRight: 10,
    paddingBottom: 12,
    paddingLeft: 10,
    borderRightWidth: 0.6,
    borderRightColor: palette.rule,
  },
  metricLast: {
    borderRightWidth: 0,
  },
  metricLabel: {
    color: palette.fog,
    fontFamily: typefaces.body,
    fontWeight: 500,
    fontSize: 6,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  metricValue: {
    marginTop: 4,
    fontFamily: typefaces.display,
    fontSize: 21,
    lineHeight: 1,
  },
  metricValueOrange: {
    color: palette.orange,
  },
  panel: {
    padding: 14,
    backgroundColor: palette.mist,
    borderRadius: 7,
  },
  panelWhite: {
    padding: 14,
    borderWidth: 0.6,
    borderColor: palette.rule,
    borderRadius: 7,
  },
  panelLabel: {
    marginBottom: 7,
    color: palette.fog,
    fontFamily: typefaces.body,
    fontWeight: 500,
    fontSize: 6,
    letterSpacing: 0.7,
    textTransform: "uppercase",
  },
  body: {
    color: palette.slate,
    fontSize: 8,
    lineHeight: 1.5,
  },
  bodyStrong: {
    color: palette.ink,
    fontFamily: typefaces.body,
    fontWeight: 600,
  },
  caption: {
    marginTop: 7,
    color: palette.fog,
    fontSize: 6.5,
    lineHeight: 1.35,
  },
  orangePill: {
    alignSelf: "flex-start",
    paddingTop: 3,
    paddingRight: 7,
    paddingBottom: 3,
    paddingLeft: 7,
    borderRadius: 2,
    backgroundColor: palette.orangeWash,
    color: palette.orange,
    fontFamily: typefaces.body,
    fontSize: 6.2,
    fontWeight: 600,
    letterSpacing: 0.85,
    textTransform: "uppercase",
  },
});
